version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ".github:"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "requirements.txt:"

  - package-ecosystem: "docker"
    directory: "/src/turbine/function-deploy"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Dockerfile:"
