name: Publish Turbine-py distributions 📦 to TestPyPI
on:
  pull_request:
    paths:
      - 'VERSION.txt'
jobs:
  build-and-publish:
    name: Build and publish Turbine-py distributions to TestPyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.4
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true # Tolerate release package duplicates ONLY ON THE TEST INDEX
