name: Semantic Release

on:
  push:
    branches: [main]
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    concurrency: push
    if: github.repository == 'meroxa/turbine-py'

    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Checkout repository
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      # packaging and dep management
      - name: Install Python Semantic Release
        run: python3 -m pip install python-semantic-release
      - name: Prep release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release publish
